language: python
python:
- '3.4'
install: pip install -r requirements.txt
script: nosetests -v test_app.py
deploy:
  provider: heroku
  api_key:
    secure: A6xKiBKh0PupwbkLv3JQgXeU8fz7JooY/b7Hfqq9H/Qe5/LSwMPb+7Jis8A/G9xpwY9okYa5q4jdvLMfrN1Uli6tVppbbqSyRm+VeeIxWYXJ27AeZQ6Lvv6mut80v0ybZu/XkgvdoY8jCJ05vbEK17TsJA0z/y6j22RoRhoU5OJZn4o2fyFy6uV0mZ2WsbIpHT2tuox5TmiXVnZ3ucOSSp0e8qHU/liJI3tzJ23AECuvIbXcFz+WDVGd+98BKfgk1IMum1fcPqyphz4ZQQKBNebkELxjY5OaQS9JqtGS6Gm/gfbu56pfa475/bXbjUbtOKEDIOQs/ezVbkKsc8lwV1trNVy4YYEHGJhmbvAMkO9Copw3bQBigGXmP6FH38HG7YtHu9vFLRXQVTo5n+z/eHs62jNVLzA4VfgrBbbbumQs08PKNC8fUVo+BGySEre6QN5C0dJpWA6DFll+JIicuhKcYTKAU6BPXkI23wB89ARNNGeMr5WJplKbGj6GWugkpMFc6+vJSBDQDbUGjE6qgzegPmu6MJTTIKpHIHnY4oledvWOEWGvpiAs7vyh2il+INjSdJmIHVZ21BETF6+dOI/h3+e6iM4lypyfX+wqqBV0krh+WbNML0g3bDDgRyLeK8kQjI9lHdp91H4yURtlTkOtA/joML+CknlM3JM4waw=
  app: yelp-and-chill
  on:
    repo: YangVincent/yelp-and-chill
    branch: vincent
  run: "web: gunicorn yelp-and-chill:app --log-file -"

