language: python
python:
- '3.4'
install: pip install -r requirements.txt
script: nosetests --with-doctest
deploy:
  provider: heroku
  api_key:
    secure: kA/0Xqk2yVned6Tp/zdJKDtfJuRQDcse+rxTlzsh7TYaoDXT+lFWj3PFz1eXG6dVLKc17u4DiK+xgdjDjrUt+Ny+O2MHul4gqVtX0sKCLw5/rtcoA2CPU4XGzADhyGRrYtLeGU4ogmIZO5NKiGFv7/W7O2Jx+E394Dl6ZofP+/Bbh/4W/GN7a4lj1tevor0xN+mDuoCYNKmBslaxfRx7zwK78BRP561xCKzeTZhzZkmk06/25NVExNaOmpVIGAZHywgcxosSeRjJvXRhfY2vT0EogAuPxXAYPVIjixYKi1tr5WDQtssyXp4qqx6uEBxYPwNBK+EaJYThzWwIBzTjbIHMkeXMg7T/MNko1nstOx+IqZAwf8/HqIzuFRGe0irkavbPvdxfUjjAnqeH/bt5zFC9dzg687ay1PsClOf95anQzdrzurWH5PkQowXgJqRprs6Wiz37GlnTj/yuc+Pznf8Bz/UpzX9oyh0P5OjoXv4y1Midx8GvZXKFmkrU2jl/MPev5LRGU3CDqaOvMQkmjhzl2ZRJ/hhiuWQVY2Y/h5RUue/0kU06uVKp9uE6rYTgz66VdhZ3hTnow7rRTF7qytF4ZICbndV3pRW37lAEw+iCo5hn45oZSp/NyKllfLl+idOyPYzqvZqbfDcZS1EQLxit0hB1i8i3mHqwx4pgZS8=
  app: yelp-and-chill
  on:
    repo: YangVincent/yelp-and-chill
    branch: vincent
  run: "web: gunicorn run:app --log-file -"

